name: .NET Workshop

on:
  push:
    branches: [ 2_hr_workshop ]
  pull_request:
    branches: [ master ]

env:
  SCREENER_API_KEY: ${{ secrets.SCREENER_API_KEY }}
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      #working-directory: './demo-csharp/DotnetCore/Sauce.Demo/'
      run: |
        cd ./DotnetCore/Sauce.Demo/
        dotnet restore
    - name: Build
      run: |
        cd ./DotnetCore/Sauce.Demo/
        dotnet build --no-restore
    - name: Test desktop web
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      run: |
        cd ./DotnetCore/Sauce.Demo/
        dotnet test ./Core.Selenium.Examples --filter TestCategory=desktop
    - name: Test emusim web
      run: |
        cd ./DotnetCore/Sauce.Demo/
        dotnet test ./Core.Selenium.Examples --filter TestCategory=emusim
    - name: Test rdc web
      run: |
        cd ./DotnetCore/Sauce.Demo/
        dotnet test ./Core.Selenium.Examples --filter TestCategory=rdc
    - name: Run all tests
      run: |
        cd ./DotnetCore/Sauce.Demo/
        dotnet test ./Core.Selenium.Examples

